# openai_api_key: "YOUR OPENAI KEY"
openai_api_key: "sk-proj-YGjCxpJsHONwBx01CHqqT3BlbkFJghxz3T8pvzeYCE47L1F5"

openai_key: "sk-proj-YGjCxpJsHONwBx01CHqqT3BlbkFJghxz3T8pvzeYCE47L1F5"
tmdb_access_token: "YOUR TMDB ACCESS TOKEN"
spotipy_client_id: "e9559fffd58c4a8a9785a644cfc01840"
spotipy_client_secret: "9283b35845fd48e6b86d540a01e99ca3"
spotipy_redirect_uri: "https://open.spotify.com/intl-fr"
YOUR_SCENARIO_KEY: "YOUR SCENARIO KEY HERE"
YOUR_SCENARIO_SECRET_IF_ANY: "YOUR SCENARIO SECRET HERE"

#spotipy_client_id: "884afca3fc194cd7a00a01210f85d826"
#spotipy_client_secret: "f0dcc4a6d3d449c5a22cd8b9e66e4d2b"
#spotipy_redirect_uri: "http://localhost/"

NOTION_KEY: "secret_8l3oBK4n08ZYUR73moFvTUTCQpmltOjbTEHxQ3T3uql"
NOTION_PAGE_ID: "ed0eab8fa04541f58a4024ecb35fde8a"
NOTION_VERSION: "2022-02-22"

UPCLICK_KEY: "pk_67500871_V516FEH5W7THCD8P7K6847IRSPFZGUJN"

discord_client_id: "1163748696425500745"
discord_client_secret: "CLp5fGdJD4avek2JpKw5j78sRP0__gNn"
discord_redirect_uri: "http://localhost/"

google_token: "ya29.a0AfB_byBW6OBtk4bTLtRV1-cK2hAP2Xg6QJeQrzstD9smG7pvbC82HxjgK403idOWAQ0DClgjho0VMTqZcEMClkkBWrj06DFw61sFLKeWYYx0KNMphlvIbsGetD7y-2RObghnGtkm4S14fp1UN44oinBgKUnxXb51vgtZFQaCgYKAbQSARISFQHGX2MiOyhHqgCd2GXPcUV1d72b2w0173"
trello_key: "41c8afc07e61972432b1a25f9fca72b2"
trello_token: "ATTAd987eb5803622814e480ea22c2a4fdcc29c999fe66a5ad5e5c12ec36f4348238275C769C"
