#create a yaml directory and file named config.yaml  inside it  and copy the below content to it and fill in the values for the keys with the respective values 

GROQ_API_KEY: ""
NOTION_KEY: ""
NOTION_PAGE_ID: ""
NOTION_VERSION: ""
OPENAI_API_KEY: ""
UPCLICK_KEY: ""
YOUR_SCENARIO_KEY: ""
YOUR_SCENARIO_SECRET_IF_ANY: ""
api_key: ""
api_version: ""
azure_deployment: ""
azure_endpoint: ""
discord_client_id: ""
discord_client_secret: ""
discord_redirect_uri: ""
elevenlabs_api_key: ""
google_token: ""
openai_api_key: ""
refresh_token: ""
speech_key: ""
spotipy_client_id: ""
spotipy_client_secret: ""
spotipy_redirect_uri: ""
tmdb_access_token: ""
trello_key: ""
trello_token: ""
zoho_refresh_token: ""
zoho_token: ""
google_client_secret : ""
client_id_secret : ""
google_client_secret : ""
google_client_id : ""

